apiVersion: batch/v1
kind: CronJob
metadata:
  name: marketplace-custom-meters-engine
  labels:
    billing: helloworld
spec:
  failedJobsHistoryLimit: 1
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: engin-cron
            cron: engine-meters-cronJob
        spec:
          containers:
          - name: engine
            image: magdysalem/custom-meters-engine:v1
          restartPolicy: Never
